# Generated by Django 3.1.2 on 2020-10-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20201003_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='grades.Courses'),
        ),
    ]
